version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - .:/app
    command: bash -c "flutter pub get && flutter build web"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    ports:
      - "80:80"
    depends_on:
      - app